;;;; -*- mode: lisp; package: user -*-
;;;;
;;;; File: hatena-star.l
;;;;
;;;; License:
;;;;
;;;;   Copyright (c) 2008 MIYAMUKO Katsuyuki.
;;;;
;;;;   hatena-star is released under an MIT license.
;;;;   See hatena-star/docs/MIT-LICENSE for full license.
;;;;

(in-package :user)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "hatena-star/api")
  (require "hatena-star/ui")
  )

(provide "hatena-star")

;;;; End
