;;; -*- mode: lisp; package: user -*-
;;;
;;; File: drive-info/ffi.l
;;;
;;; License:
;;;
;;;   Copyright (c) 2007 MIYAMUKO Katsuyuki.
;;;
;;;   drive-info is released under an MIT license.
;;;   See drive-info/docs/MIT-LICENSE for full license.
;;;

(in-package :user)

(require "drive-info/ffi/package")
(require "drive-info/ffi/types")
(require "drive-info/ffi/kernel32")

(provide "drive-info/ffi")

;;; End
