;;; -*- Mode: Lisp; Package: user -*-
;;; box-fixation-mode.l --- box-fixation-mode.l の ni-autoload 用モジュール

;; Copyright (C) 2001-2005 OHKUBO Hiroshi <ohkubo@s53.xrea.com>

;; Author: OHKUBO Hiroshi <ohkubo@x53.xrea.com>
;; Time-stamp: <2005/10/08 14:53:03 +0900>

;; Description:
;;
;;     box-fixation-mode.l の ni-autoload 用モジュール
;;

; 起動時から使用するためrequireで読み込む
(require "box-fixation-mode")

;;; box-fixation-mode.l ends here
