;;; -*- Mode: Lisp; Package: user -*-
;;; clickable-uri.l --- clickable-uri.l の ni-autoload 用モジュール

;; Copyright (C) 2001-2005 OHKUBO Hiroshi <ohkubo@s53.xrea.com>

;; Author: OHKUBO Hiroshi <ohkubo@s53.xrea.com>
;; Time-stamp: <2005/10/08 12:02:13 +0900>

;; Description:
;;
;;     clickable-uri.l の ni-autoload 用モジュール
;;

; 起動時から使用するためrequireで読み込む
(require "clickable-uri")

;;; clickable-uri.l ends here
