;;; -*- Mode: Lisp; Package: user -*-
;;; insert-directory-tree.l --- insert-directory-tree の ni-autoload 用モジュール

;; Copyright (C) 2001-2005 OHKUBO Hiroshi <ohkubo@s53.xrea.com>

;; Author: OHKUBO Hiroshi <ohkubo@s53.xrea.com>
;; Time-stamp: <2005/10/08 15:01:55 +0900>

;; Description:
;;
;;     insert-directory-tree の ni-autoload 用モジュール
;;

; 任意の時点で実行するのでautoloadで読み込む
(autoload 'insert-directory-tree "insert-directory-tree" t)

;; insert-directory-tree.l ends here
