;;; -*- Mode: Lisp; Package: user -*-
;;; keep-window-line.l --- keep-window-line.l の ni-autoload 用モジュール

;; Copyright (C) 2001-2005 OHKUBO Hiroshi <ohkubo@s53.xrea.com>

;; Author: OHKUBO Hiroshi <ohkubo@s53.xrea.com>
;; Time-stamp: <2005/10/08 14:56:12 +0900>

;; Description:
;;
;;     keep-window-line.l の ni-autoload 用モジュール
;;

; 起動時から使用するためrequireで読み込む
(require "keep-window-line")

;;; keep-window-line.l ends here
