;;; -*- Mode: Lisp; Package: user -*-
;;; multiple-replace.l --- multiple-replace.l の ni-autoload 用モジュール

;; Copyright (C) 2001-2005 OHKUBO Hiroshi <ohkubo@s53.xrea.com>

;; Author: OHKUBO Hiroshi <ohkubo@s53.xrea.com>
;; Time-stamp: <2005/10/08 12:33:05 +0900>

;; Description:
;;
;;     multiple-replace.l の ni-autoload 用モジュール
;;

; 起動時から使用するためrequireで読み込む
(require "multiple-replace")

;; multiple-replace.l ends here
