;;; -*- Mode: Lisp; Package: user -*-
;;; pickup-pattern.l --- pickup-pattern.l の ni-autoload 用モジュール

;; Copyright (C) 2001-2005 OHKUBO Hiroshi <ohkubo@s53.xrea.com>

;; Author: OHKUBO Hiroshi <ohkubo@s53.xrea.com>
;; Time-stamp: <2005/10/08 12:14:17 +0900>

;; Description:
;;
;;     pickup-pattern.l の ni-autoload 用モジュール
;;

; 起動時から使用するためrequireで読み込む
(require "pickup-pattern")

;;; pickup-pattern.l ends here
