; -*- mode: lisp; package: user -*-

;;; hatena-star/ui.l
;;
;; Copyright (c) 2008 MIYAMUKO Katsuyuki.
;;
;; hatena-star is released under an MIT license.
;; See hatena-star/docs/MIT-LICENSE for full license.
;;

;;; Code:

(in-package :user)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (require "hatena-star/ui/config")
  (require "hatena-star/ui/formatter")
  )

(provide "hatena-star/ui")

;;; End
