;;; -*- Mode: Lisp; Package: user -*-
;;; box-fixation-mode.l --- box-fixation-mode.l の uninstall 用モジュール

;; Copyright (C) 2001-2005 OHKUBO Hiroshi <ohkubo@s53.xrea.com>

;; Author: OHKUBO Hiroshi <ohkubo@s53.xrea.com>
;; Time-stamp: <2005/10/08 14:53:33 +0900>

;; Description:
;;
;;     box-fixation-mode.l の uninstall 用モジュール
;;

(require "box-fixation-mode")
(ed::box-fixation-mode-uninstall)

;;; box-fixation-mode.l ends here
